Add dummy text into styles.css because the release action demands it
>HTTP 400: Bad Content-Length (https://uploads.github.com/repos/Sanqui/obsidian-persistent-graph/releases/328506976/assets?label=&name=styles.css)
>Error: Process completed with exit code 1.

https://github.com/Sanqui/obsidian-persistent-graph/actions/runs/26362421860/job/77600173931